name: Stats

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repos 
        uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
           python-version: '3.11'
      - name: Run script
        run: python ./laboratorio/prueba-action/main.py
